backend:
  name: github
  repo: deepakness/deepakness-main

media_folder: static
public_folder: ../static

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: ogimage, label: ogImage, widget: "image" }
      - { name: body, label: Body, widget: markdown }
